filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["https://elastic1:9200", "https://elastic2:9200", "https://elastic3:9200"]
  ssl.certificate: /certs/filebeat.crt
  ssl.key: /certs/filebeat.key
  username: "elastic"
  password: "${ES_PASSWORD}"
  ssl.certificate_authorities: /certs/elk-ca.crt
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
